// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6mpkbpXv_haNtskZaWRT_C-f5AL_pUCQ',
    appId: '1:881064006117:web:03bdc8ff7c9f4cda0cdf0c',
    messagingSenderId: '881064006117',
    projectId: 'registro-usuarios-d943f',
    authDomain: 'registro-usuarios-d943f.firebaseapp.com',
    databaseURL: 'https://registro-usuarios-d943f-default-rtdb.firebaseio.com',
    storageBucket: 'registro-usuarios-d943f.firebasestorage.app',
    measurementId: 'G-WTX0RHY683',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8uTRSLSSL786JzIAUPPhuUmsrncgSwnc',
    appId: '1:881064006117:android:67041c7e4862e5a90cdf0c',
    messagingSenderId: '881064006117',
    projectId: 'registro-usuarios-d943f',
    databaseURL: 'https://registro-usuarios-d943f-default-rtdb.firebaseio.com',
    storageBucket: 'registro-usuarios-d943f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqqCMQm1GVFNREJp-BI5Q3TsksOx8POkM',
    appId: '1:881064006117:ios:07dfd8e7a151ed5e0cdf0c',
    messagingSenderId: '881064006117',
    projectId: 'registro-usuarios-d943f',
    databaseURL: 'https://registro-usuarios-d943f-default-rtdb.firebaseio.com',
    storageBucket: 'registro-usuarios-d943f.firebasestorage.app',
    iosBundleId: 'com.example.tiendaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqqCMQm1GVFNREJp-BI5Q3TsksOx8POkM',
    appId: '1:881064006117:ios:07dfd8e7a151ed5e0cdf0c',
    messagingSenderId: '881064006117',
    projectId: 'registro-usuarios-d943f',
    databaseURL: 'https://registro-usuarios-d943f-default-rtdb.firebaseio.com',
    storageBucket: 'registro-usuarios-d943f.firebasestorage.app',
    iosBundleId: 'com.example.tiendaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6mpkbpXv_haNtskZaWRT_C-f5AL_pUCQ',
    appId: '1:881064006117:web:51881724d7e8f7a10cdf0c',
    messagingSenderId: '881064006117',
    projectId: 'registro-usuarios-d943f',
    authDomain: 'registro-usuarios-d943f.firebaseapp.com',
    databaseURL: 'https://registro-usuarios-d943f-default-rtdb.firebaseio.com',
    storageBucket: 'registro-usuarios-d943f.firebasestorage.app',
    measurementId: 'G-C9HPJJ3D7H',
  );
}



